language: python
sudo: true
python:
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - pypy
    - pypy3
install:
    - "pip install -r requirements.txt"
    - "pip install -r requirements-dev.txt"
    - "pip install -r requirements-extends.txt"
    - "pip install codecov"
script: make test
branches:
    only:
        - master
after_success:
    codecov
