language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
install:
    - "sudo pip install -r requirements.txt"
    - "sudo pip install -r requirements-dev.txt"
    - "sudo pip install -r requirements-extends.txt"
script: make test
branches:
    only:
        - master
after_success:
    - bash < (curl -s https://codecov.io/bash)
